app.py
from flask import Flask
from routes.home import home_route
from routes.clientes import cliente_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')


app.run(debug=True)

routes/clientes.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def lista_clientes():
    return render_template('lista_clientes.html', clientes=CLIENTES)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    data = request.json

    novo_usuario = {
        "id": len(CLIENTES)+1,
        "nome": data['nome'],
        "email": data['email'],

    }

    CLIENTES.append(novo_usuario)

    return render_template('item_cliente.html', cliente=novo_usuario)

@cliente_route.route('/new')
def form_cliente():
    return render_template('form_cliente.html')

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    return render_template('detalhe_cliente.html')

@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    cliente = None
    for c in CLIENTES:
        if c['id'] == cliente_id:
            cliente = c
    
    return render_template('form_cliente.html', cliente=cliente)

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):
    cliente_editado = None
    data = request.json
    for c in CLIENTES:
        if c['id'] == cliente_id:
            c['nome'] = data['nome']
            c['email'] = data['email']
            
            cliente_editado = c
            
    return render_template('item_cliente.html', cliente=cliente_editado)

@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):   
    global CLIENTES
    CLIENTES = [ c for c in CLIENTES if c['id'] != cliente_id ]
    return {'deleted': 'ok'}

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form_cliente.html
<form class="c-form" 
        {% if cliente %}
        action="{{ url_for('cliente.atualizar_cliente', cliente_id=cliente.id) }}" 
        {% else %}
        action="{{ url_for('cliente.inserir_cliente') }}"
        {% endif %}

        method="{% if cliente %}PUT{% else %}POST{% endif %}"

        {% if cliente %}
            c-swap="#cliente-{{cliente.id}}"
        {% else %}
           c-append="#lista-clientes"

        {% endif %}
>

    <div class="mb-3">
        <label class="form-label">Nome</label>
        <input type="text" class="form-control" name="nome" {% if cliente%}value="{{cliente.nome}}"{% endif %}>
    </div>

    <div class="mb-3">
        <label id="label-target" class="form-label">Email</label>
        <input type="text" class="form-control" name="email" {% if cliente%}value="{{cliente.email}}"{% endif %}>
    </div>

    <button type="submit" class="btn btn-primary">
        {% if cliente %}Salvar{% else %}Criar{% endif %}
    </button>
</form>

templates/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
</head>

<body>
    <div class="container">
        <h1>Gestão de Clientes</h1>

        <div id="form-cliente" c-container="{{ url_for('cliente.form_cliente') }}"></div>
        <hr>
        <h2>Lista de Clientes</h2>
        <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>

</html>

templates/item_cliente.html
<tr id="cliente-{{cliente.id}}">
    <th scope="row">{{cliente.id}}</th>
    <td>{{cliente.nome}}</td>
    <td>{{cliente.email}}</td>
    <td>
        <button class="btn btn-primary" 
            c-get="{{ url_for('cliente.form_edit_cliente', cliente_id=cliente.id) }}"
            c-target="#form-cliente">
                Editar
        </button>

        <button class="btn btn-danger" 
        c-delete="{{ url_for('cliente.deletar_cliente', cliente_id=cliente.id) }}" c-remove-closest="tr">
        Excluir
        </button>

    </td>
  </tr> 

templates/lista_clientes.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista-clientes">
        {% for cliente in clientes%}
            {% include 'item_cliente.html'%}
        {% endfor %}
    </tbody>
  </table>